server:
  port: 8081
spring:
  application:
    name: server-a
  r2dbc:
    url: r2dbc:mysql://localhost:3306/server_a_db
    username: root
    password:
    pool:
      initial-size: 50
      max-size: 500
      max-idle-time: 30s
      validation-query: "SELECT 1"
  data:
    redis:
      host: localhost
      port: 6379
      database: 11
      lettuce:
        pool:
          max-active: 50
          max-idle: 20
          min-idle: 10
          max-wait: 500ms
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
      batch-size: 16384
      compression-type: gzip

request:
  duplicateLimit: 3 # 중복 요청 최대 허용 횟수
